---
abstract: 'Utility object to extract OS Code-Point Open data for British Postcodes'
author:
  - 'Michael Jemmeson <mjemmeson@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  List::Util: 0
  Test::More: 0
  Test::Most: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
  Module::Build::Tiny: 0.034
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-UK-Postcode-CodePointOpen
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Geo::Coordinates::OSGB: 0
  Geo::UK::Postcode::Regex: 0
  Moo: 0
  Path::Tiny: 0.048
  Text::CSV: 0
  Types::Path::Tiny: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/mjemmeson/Geo-UK-Postcode-CodePointOpen/issues
  homepage: https://github.com/mjemmeson/Geo-UK-Postcode-CodePointOpen
  repository: https://github.com/mjemmeson/Geo-UK-Postcode-CodePointOpen.git
version: 0.004
